Добавление проекта в основной репозиторий
java-park-mail-ru/tower-defence-09-2016 pull request #1
Opened 2016-10-27 15:16 UTC by SannikovDmitry

2016-11-10 14:30 UTC, d-frolov requested changes
По коду вопросов нет. Выкиньте пожалуйста все idea-вские файлы и .iml  файл и я приму реквест

2016-12-17 10:37 UTC, SannikovDmitry commented
Удалено

2016-12-18 22:21 UTC, KSolovyev commented
Вы смешали код к 1РК с кодом ко 2РК. Так смотреть очень не удобно. Сейчас здесь весь код, который есть у вас?

2016-12-18 22:52 UTC, SannikovDmitry commented
Константин, пока да.

2017-01-14 19:54 UTC, SannikovDmitry commented
Обновил репозиторий, добавил основные компоненты.
Игровую механику добавлю в самое ближайшее время, так как возникли непредвиденные проблемы с фронтовой частью. 
Исправляем.

2017-01-16 19:13 UTC, KSolovyev commented
Ребята, этого мало. У вас есть что-нибудь еще?

2017-01-16 20:53 UTC, SannikovDmitry commented
Константин, понимаю, проект доделывал я один, так как мои ребята из команды слились окончательно.
Правил также на фронтенде многие вещи. На этом из рабочего кода у меня все, мультиплеер пытаюсь сделать, но он пока не рабочий, единственное сегодня и вчера не делал, так как экзамен нужно было сдать.
Нужно, буду доделывать мультиплеер. Если уже нет, то нет.

2017-10-16 09:26 UTC, closed without merging